services:
  backend:
    build:
      context: ../musicme-backend-hono
    ports:
      - "3000:3000"
    env_file:
      - ../musicme-backend-hono/.env
    volumes:
      - ../musicme-backend-hono:/src  
      - /src/node_modules 
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: .
    ports:
      - "4000:4000" 
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - .:/app  
      - /app/node_modules
    command: ["npm", "run", "dev"]
